# Generated by Django 5.1.1 on 2024-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='type',
            field=models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('H', 'Health'), ('S', 'School'), ('O', 'Others')], default='', max_length=2),
        ),
    ]
